name: Standalone

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: CXX=g++-9 CC=gcc-9 cmake -Hstandalone -Bbuild

    - name: build
      run: cmake --build build -j4

    - name: run
      run: ./build/LuaGlue
