name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: install valgrind
      run: sudo apt install -y valgrind

    - name: configure
      run: cmake -Htest -Bbuild -DCMAKE_BUILD_TYPE=Debug

    - name: build
      run: cmake --build build -j4
        
    - name: test
      run: cmake --build build -j4
        
    - name: run tests with valgrind
      run: valgrind --track-origins=yes --error-exitcode=1 --leak-check=full ./build/LuaGlueTests
